# Site Info
title: '0xF4D3C0D3 Blog'
tagline: 'AWS, Forensic, Python, Web'
description: 'DESCRIPTION'
baseurl: ""
url: https://0xb4df4c3d.github.io/
logo: 'https://avatars2.githubusercontent.com/u/19762154?s=460&v=4'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: 0xF4D3C0D3
  description: I like computer, and also something like geeks
  gravatar: 2835edab17b38538a5fdab5f1d11d3d9 # md5 hash of your email address
  contact:
    #linkedin:
    github:    https://github.com/0xB4DF4C3D/
    facebook:  https://www.facebook.com/JungDongH0
    #twitter:   https://twitter.com/Li_Zhihao
    #weibo:     http://weibo.com/41173780
    email:     dongho971220@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/insufficient_data.jpg
  caption: WELCOME! Click right-upper menu!

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-114733186-1' # leave blank if you don't want google analytics
disqus_short_name: 'github-io-6' # leave blank if you don't want disqus
